server:
  port: 8081
spring:
  session:
    store-type: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/quizz_web
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
